A little cleanup
salt-formulas/salt-formula-etcd pull request #4
Opened 2016-09-25 06:08 UTC by cznewt

2016-09-25 16:17 UTC, pupapaik commented
Did you test following changes? and can you push single commit?

2016-09-25 16:18 UTC, pupapaik commented on etcd/server.sls
> +{%- if server.engine == 'kubernetes' %}
This should be there. Remove this from map.jinja. Default is container.

2016-09-25 16:19 UTC, pupapaik commented on README.rst
> -        members:
Why did you delete this?

2016-09-25 16:19 UTC, pupapaik commented on etcd/map.jinja
> +        'engine': 'systemd'
systemd is not default.

2016-09-25 16:19 UTC, pupapaik requested changes
Please check my comments.

2016-09-26 07:12 UTC, fpytloun commented on etcd/server.sls
> +{%- if server.engine == 'kubernetes' %}
Defaults should be defined in map.jinja or using `get('xyz', default)` or `|default(default)` jinja filter.

2016-09-26 07:13 UTC, fpytloun commented on etcd/server.sls
> +  - source: salt://etcd/files/etcd.manifest
I preffer 2-space indent for lists which is IMHO correct YAML approach, while both are working fine.

2016-09-26 07:14 UTC, fpytloun commented on etcd/server.sls
> +  - user: root
Maybe don't define defaults (user/group, mode) as it's useless

2016-09-26 08:24 UTC, fpytloun commented on etcd/server.sls
> +  - source: salt://etcd/files/etcd.manifest
And it's wrong by specs!
http://yaml.org/spec/1.2/spec.html
> Example 8.3. Invalid Block Scalar Indentation Indicators
```
ERROR:
- A leading all-space line must
  not have too many spaces.
- A following text line must
  not be less indented.
- The text is less indented
  than the indicated level.
```

2016-09-26 08:24 UTC, fpytloun requested changes

2017-05-02 13:03 UTC, fpytloun commented
Old review with conflicts, closing

2017-05-02 13:03 UTC, closed without merging